### ISSUE TITLE
Is it possible to reference an external file as a content file?

### ISSUE THREAD

**Issue by stephen-swensen** [quamotion/dotnet-packaging#226]
Let's say I have buillt a package like `myapp.deb` and distribute it to customers along with a customer-specific config file like `myapp.cfg`... when installing `myapp.deb` from a directory with `myapp.cfg` placed along side of it, is it possible for `myapp.deb` to reference the external file (relative to the directory being installed from, like a home directory) so that it is copied to the application installation directory (like `/usr/share/myapp/myapp.cfg`)? Bonus if installation aborts if the file is missing.

Thanks!

**Comment by atauenis** [comment]
Made a separate package, say, `myapp-company-branding`, which will install brand configuration to `/etc/myapp.conf.d/` directory (`myapp` should read configuration from it). This is correct UNIX-way, and this is used by some Linux distributions to apply branding.

**Comment by stephen-swensen** [comment]
Hmm, I see - I'll think on that, thanks. I am a bit hesitant to go down that road because the work I am doing is extending Linux support to an app that currently just supports Windows. I want to minimize code and distribution differences (the Windows app is distributed as an MSI like `myapp.msi` which picks up the external `myapp.cfg` and copies it to the installation directory, so I was wanting to replicate that as near as possible; the app also expects the configuration file to be present from the directory path of the executable, so I'd rather avoid platform specific differences there too).

**Comment by stephen-swensen** [comment]
Maybe debconf could be used somehow to prompt the user for the location of the config file and use it in a preinstall script to copy the file 🤔 

Anyways, I'll go ahead and close this Issue if there is no direct way to do this through dotnet deb. Thanks for your insight!

**Comment by stephen-swensen** [comment]
It's definitely hacky / fragile, but I was able to do what I was looking for with a preinstall script like:

```
  <PropertyGroup>
    <PreInstallScript>
      <![CDATA[mkdir -p /usr/share/myapp && find /home -type f -name 'myapp.cfg' | xargs cp -t /usr/share/myapp/]]>
    </PreInstallScript>
  </PropertyGroup>
```
