### ISSUE TITLE
dotnet deb install failed

### ISSUE THREAD

**Issue by sbannikov** [quamotion/dotnet-packaging#233]
Just tried to use your utility. 
`dotnet tool install --global dotnet-deb` command was successful.
But now  I am stuck at:
`C:\GIT\ProjectFolder>dotnet deb install`
`Unhandled exception. System.InvalidOperationException: No instances of MSBuild could be detected.`
`Try calling RegisterInstance or RegisterMSBuildPath to manually register one.`
`at Microsoft.Build.Locator.MSBuildLocator.RegisterDefaults()`
`at Dotnet.Packaging.PackagingRunner..ctor(String outputName, String msbuildTarget, String commandName) in /__w/1/s/dotnet-rpm/PackagingRunner.cs:line 29`
`at Dotnet.Packaging.Program.Main(String[] args) in /__w/1/s/dotnet-deb/Program.cs:line 9`         
 I tried to figure out what's happenning but failed.
Defintely I have both Microsoft Visual Studio 2022 with MSBuild installed. 
Could anyone help me wth this issue?   Thanks!

**Comment by sbannikov** [comment]
I made some additional investigation and found, that .NET SDK 6.0 should be installed as a separate installation to use this package. Visual Studio installation isn't sufficient (ir maybe I missed some additional component).
I suggest that it should be explicitely noted in readme/manual.

**Comment by pyking-wang** [comment]
Hello, I have also encountered this issue. Have you solved it? thank you

**Comment by atauenis** [comment]
I can confirm that Visual Studio 2019 with separately installed .NET SDK 6.0 can work with `dotnet-packaging` (old Windows & Visual Studio versions are not barriers to work on .NET 6 apps). How about Win10/11 & default installation of VS2022 I'm don't know at this moment.

**Comment by cancelpj** [comment]
> I can confirm that Visual Studio 2019 with separately installed .NET SDK 6.0 can work with `dotnet-packaging` (old Windows & Visual Studio versions are not barriers to work on .NET 6 apps) without problems. How about Win10/11 & default installation of VS2022 I'm don't know at this moment.

The same on VS2022.

**Comment by newtocodeC** [comment]
> Hello, I have also encountered this issue. Have you solved it? thank you

 Have you solved it? Same situation，Same error
