### ISSUE TITLE
I don't have  "control.tar.gz" and "debian-binary" in the deb file I packaged

### ISSUE THREAD

**Issue by ApaulMyLittleAirport** [quamotion/dotnet-packaging#250]
I Use "dotnet msbuild MyApp.csproj /t:CreateDeb /p:SelfContained=true /p:RuntimeIdentifier=linux-x64 /p:Configuration=Release" to create .deb file，but it not have  "control.tar.gz" and "debian-binary"，only have a "data.tar"
Please guide me on what I can do, thank you very much!

**Comment by atauenis** [comment]
How do you testing the contents? WinRAR & 7-Zip seems to incorrectly displaying contents of .deb packages. And the Dotnet-Packaging generated debs are installing without problems (at least where I've tested, but probably anywhere).

**Comment by ApaulMyLittleAirport** [comment]
> How do you testing the contents? WinRAR & 7-Zip seems to incorrectly displaying contents of .deb packages. And the Dotnet-Packaging generated debs are installing without problems (at least where I've tested, but probably anywhere).

I have successfully resolved it, thank you!
