### ISSUE TITLE
Creating a .deb from Release instead of Debug

### ISSUE THREAD

**Issue by CryoViking** [quamotion/dotnet-packaging#253]
This might've already been asked before, but I can't seem to easily find an existing issue nor did I see a clear way to do it on the README.

Is there a way I can run ``dotnet deb`` and have it build a ``*.deb`` file from the result of ``dotnet publish`` instead of ``dotnet build``?

**Comment by atauenis** [comment]
`dotnet deb -c Release -r linux-x64`
or:
`dotnet publish -c Release -r linux-x64 -t:CreateDeb,Clean`

All (or almost all) popular arguments for `dotnet publish` are working with `dotnet deb`. And with `-t:` argument it's possible to specify a longer set of commands, like `CreateDeb,CreateRpm,Clean`.

**Comment by CryoViking** [comment]
Thanks for the answer, I had figured it out like 30 minutes later but forgot to close the issue. My next thing is figuring out how to run a preinst and postinst script

**Comment by atauenis** [comment]
> My next thing is figuring out how to run a preinst and postinst script

Resave the csproj file to use LF line endings, and put scripts inside `<PropertyGroup> <PostInstallScript><![CDATA[   ]]></PostInstallScript>` (`<PreRemoveScript>`).
